albums = ["Silent Shout","Niggas on the moon ","Loveless ","Ok Computer ","Government plates ","Selected ambient works 1985-1992","Crystal Castles I",
"Drive(OST)","Sehnsucht ","Shaking the habitual ","Fever Ray","Odyssey","Blacklist ","Good for your soul","Unknown Pleasures ","Witch Hour","BLANK BANSHEE 0",
"CLPPNG","Davos","Bottomless pit","Jenny Death","Deep cuts","Run the Jewels 2","Paprika(OST)","Berserk(OST)","Filth ","Amnesiac ","Atrocity exhibition ",
"The day is my enemy ","Crystal castles II","Moon ep ","Reise,reise ","Lift Your Skinny Fists Like Antennas to Heaven","No love deep web","Herzleid ","Dare!",
"Atrocity Exhibition","XXX","Niggas on the Moon","Jenny Death","Run the Jewels 2","A Grand Don't  Come For Free","Hold Your Colour","Crystal Castles","CLPPING",
"Blank Banshee 0","FLCL OST 3","Cowboy Bebop OST 4 - Blue","Invaders Must Die","OK Computer ","Bottomless Pit","Immersion","Paprika OST","Divide And Exit",
"Yeezus","Filth ","Twilight","Wriggle","Biophilia","Obscure but Visible","Black Up","Exmilitary","Moon Money","Close to the edge","The Yes album","Aqualung",
"Demons and Wizards","Benzaiten","The Iron Horse","Dreams","Sleeps Holy Mountain","Songs about Fucking","Untrue","ILLmatic","Land of Rape and Honey",
"Blues for the Red Sun","Facelift","Come my Fanatics","Heartwork","Lifeforms","Advaitic Songs","Moving Pictures","Debut","Hi,How are you?","The low end theory",
"Monoliths and Dimensions","In the City","Damaged","Banned in D.C.","Tweez","Skag Heaven","Dirt","Deathconsciousness","Bleach","Untitled","Daydream Nation",
"Goo","Scum","Siamese Dream","Death,Pierce me","Vol.4","Odelagt","Litourgiya","2001","My Love is cool (Deluxe Edition)","Graduation","xx",
"No need to argue","The Stone Roses","Burn the Maps","Mellon collie and the infinite sadness","Beauty Behind the madness","Nevermind","The Lumineers",
"In Silico","Electric Ladyland","Goo","Daydream Nation","Rumours","Live and Dangerous","Back in Black","Back Through Time",
"Born in the USA, Died in apartment 48","LA Woman","MTV Unplugged","Jenny Death","Rum, Sodomy & the Lash","A Grand Don't Come for Free",
"Captain Morgan’s Revenge","Toxicity","American Idiot","Fleetwood Mac (1975)","(What’s the Story) Morning Glory?","Wish You Were Here"];
artists = ["The knife","Death Grips ","My bloody Valentine ","Radiohead ","Death Grips ","Aphex Twin ","Crystal Castles ","Cliff Martinez ",
"Rammstein ","The Knife ","Fever Ray ","Home","Kap Bambino ","Oingo Boingo ","Joy division ","Ladytron","Blank Banshee ","Clipping ","Computer magic ",
"Death Grips ","Death Grips ","The knife ","Run the Jewels ","Hirasawa Susumu","Hirasawa Susumu ","Swans ","Radiohead ","Danny Brown ","The prodigy ",
"Crystal Castles","M|O|O|N","Rammstein","Godspeed you!Black emperor ","Death Grips","Rammstein ","Human League ","Danny Brown","Danny Brown ","Death Grips",
"Death Grips","Run the Jewels","The Streets","Pendulum","Crystal Castles","Clipping","Blank Banshee","The Pillows","The Seatbelts","The Prodigy","Radiohead ",
"Death Grips ","Pendulum","Susumu Hirasawa ","Sleaford Mods","Kanye West ","Swans","Bôa","Clipping","Björk","Computer Magic","Shabazz Palaces","Death Grips",
"Hot Sugar","Yes","Yes","Jethro Tull ","Uriah Heep ","Osamu Kitajima","The sound defects ","Gabor Szabo","Sleep","Big Black","Burial","NAS","Ministry",
"Kyuss","Alice in Chains","Electric Wizard","Carcass ","Future Sound of London","Om","Rush","Bjork","Daniel Johnston ","A Tribe Called Quest","Sunn O)))",
"The Jam","Black Flag","Bad Brains","Slint","Squirrel Bait","Alice in Chains ","Have a Nice Life","Nirvana","Slint","Sonic Youth","Sonic Youth","Napalm Death",
"Smashing Pumpkins","Silencer","Black Sabbath","Trencadis","Batushka","Dr.Dre","Wolf Alice","Kanye West","The xx","The Cranberries ",
"The Stone Roses","The Frames","Smashing Pumpkins","The Weeknd","Nirvana","The Lumineers","Pendulum","Jimi Hendrix","Sonic Youth","Sonic Youth","Fleetwood Mac",
"Thin Lizzy","AC/DC","Alestorm","Bruce Springsteen","The Doors","Nirvana","Death Grips","The Pogues","The Streets","Alestorm","System of a Down","Green Day",
"Fleetwood Mac","Oasis","Pink Floyd"]
